<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
<!--        <TargetFramework>net10.0</TargetFramework>-->
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
        <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Ical.Net" />
        <PackageReference Include="LanguageExt.Core" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="MiniValidation" />
        <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CalendarApp.Contracts\CalendarApp.Contracts.csproj" />
      <ProjectReference Include="..\CalendarApp.ServiceDefaults\CalendarApp.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
