<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>88e15a2f-d8d3-4f5e-a807-965fce2482bc</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost"/>
        <PackageReference Include="Aspire.Hosting.SqlServer" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.SqlServer.Extensions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CalendarApp.API.Migrator\CalendarApp.API.Migrator.csproj" />
      <ProjectReference Include="..\CalendarApp.API\CalendarApp.API.csproj" />
      <ProjectReference Include="..\CalendarApp.Web\CalendarApp.Web\CalendarApp.Web.csproj" />
    </ItemGroup>

</Project>
